### PR TITLE
Use NbClust package to determine best number of clusters

### PR DESCRIPTION
**Pull request by catterbu**
This pull request adds a new method for determining the best number of clusters in `multi_clust` to use for a given data set. Specifically,
- `validate_num_data` now returns a boolean variable indicating whether or not the data set fed into it is boolean or not. Previously, it simply sent a message to the screen when this was the case.  
- The `NbClust` function was brought in from the _NbClust_ package, based on the GNU public license, and adapted to be more robust in cases where not all algorithms can be used.  
- `multi_clust` calls the `NbClust` function to determine the ideal number of clusters for a data set, labeled `k_best` in the _multiClust_ object.  
- `multi_clust` leverages the new variable returned by `validate_num_data` to call `NbClust` differently if a binary data set is being used.

### CODE REVIEW

**Comment by nsh87** [comment]
@catterbu: how are those unit tests for boolean data working out? let me know when this seems fully tested and ready to merge.

**Comment by catterbu** [comment]
@nsh87 Yeah, pretty much done. Had a weird last couple of days, but I think that I have everything figured out. I just have to dirty that data set I created, integrate the changes you just added via rebase, and then make sure that everything is good.

**Comment by nsh87** [comment]
@catterbu: [this](https://github.com/catterbu/receptormarker/commit/b69211dd70d5511b3ac22a5fb39e9229904e3401#diff-d967db195f823be193f8c07caafb7d98R55) isn't correct anymore, is it? It should say that it's chosen by majority rule using a bunch of different algorithms, right?

**Comment by catterbu** [comment]
@nsh87 the documentation for the **multiClust** object appears to have updated properly. Let me know if I missed something. 
Chris

**Comment by nsh87** [comment]
@catterbu: Not sure what this is referring to:
"@nsh87 the documentation for the **multiClust** object appears to have updated properly. Let me know if I missed something."

**Comment by catterbu** [comment]
@nsh87 you had a comment about the docs needing to be updated. Maybe I misinterpreted it on my phone.

**Comment by nsh87** [comment]
@catterbu: you had documented `multiClust` in two different functions (basically copying the documentation in one to the other). You updated one of them, but not the other. So rather than deal with this again when COMMUNAL is used, I'm just creating an actual class where the documentation for `multiClust` can live and it can just be referenced from whatever functions you want. I'll have to update some of the code since referencing slots in a class is done with `@`, not the typical indexing with `[ ]`.

**Comment by catterbu** [comment]
@nsh87 got it.

**Comment by nsh87** [comment]
@catterbu: maybe I missed it, but did you generate a new `multiClust` object `f_clust.rda` for use in the unit tests, or is it still the old one?

**Comment by catterbu** [comment]
@nsh87 No! I forgot to look up how to do that.

**Comment by nsh87** [comment]
@catterbu: it's just `save(object_to_save, file="filename.rda")`,then move it where you want to.

**Pull request merged**
