### PR TITLE
Fix error handling in multi_clust

### PR DESCRIPTION
**Pull request by catterbu**
This PR just contains a single commit to make more robust error handling that returns a specific message when a known error arises and else returns the error as R put it out.

### CODE REVIEW

**Comment by nsh87** [comment]
Just a note: this will fail until the test function for creating a multiClust object with boolean data can pass.

**Comment by catterbu** [comment]
@nsh87 I think that we should close this PR without merging it in. I just went through this branch and everything of relevance is now already in **dev**. The only other stuff is for _NbClust_. I merged all _NbClust_ stuff into a separate branch devoted to that. Thoughts?

**Comment by nsh87** [comment]
I thought this was specifically made to handle NbClust errors...? Are you saying that these changes are in a separate branch now or are in dev, or did I miss the point of the PR?

**Comment by catterbu** [comment]
@nsh87 right, this was made to handle NbClust errors. I merged it into a separate local branch. Since we have not even made a working version of NbClust, it does not make sense to have a branch fixing errors in it.

**Comment by catterbu** [comment]
@nsh87 I will be working on NbClust soon, but I figured I should just merge all of that into one branch and then start a single PR once I have gone through it.

**Comment by nsh87** [comment]
Ah, I see. I reverted calling `NbClust` in 46d3e4ed29d15d9cc2d45e40c9ad18a3866da6d9 due to some errors. Ok, I'll close this.

**Pull request closed without merging**
