### PR TITLE
Add legend to PCA plot

### PR DESCRIPTION
**Pull request by catterbu**
This PR adds a legend outside the PCA plot that identifies the cluster assignments indicated by each color.

### CODE REVIEW

**Comment by catterbu** [comment]
@nsh87 after all of the difficulties with the other branch, I just decided to get a fresh branch from _dev_ and add the one commit there.

**Comment by catterbu** [comment]
@nsh87 This PR failed due to stylistic things. None of these was changed since I branched off of _dev_. Let me know if there is something that I should do.

**Comment by nsh87** [comment]
@catterbu That's strange...can you fix it on your local so it works? Use `devtools::test()` so you don't have to push up to Travis to see if it passes.

**Comment by catterbu** [comment]
@nsh87 `devtools::test()` passes with only the biopython warnings. Not sure why travis does not agree.

**Comment by nsh87** [comment]
@catterbu this has some unrelated commits in it (change check for boolean data). maybe needs a rebase off of dev?

**Comment by catterbu** [comment]
@nsh87 this is strange because the two commits above `Add pca legend` are both both from a rebase off of the **dev** branch. I will try rebasing off of **dev** again, see if everything is sorted, and potentially use an interactive rebase, if required.

**Comment by catterbu** [comment]
@nsh87 looks like that rebase corrected everything. I needed to incorporate the merge of the other pull request from me anyhow.

**Comment by nsh87** [comment]
Closing in favor of PR #65.

**Pull request closed without merging**
