### PR TITLE
Create a radial phylogram htmlwidget

### PR DESCRIPTION
**Pull request by nsh87**
This adds a function `radial_phylo()` that can be used to generate a radial phylogram using D3 and a number of other JavaScript libraries. It has function arguments that allow for condensing the radial phylogram, adding outer rings to annotate the sequences, adjusting the font size, and more. See the function documentation for more details.

The function favors using Biopython to build the tree, warning users if Biopython is not available, but falls back to using R packages if Biopython is not available.

The documentation of the function includes an example using a provided data set (single-cell TCR data with phenotypic markers, as a data.frame) which can be used with other functions.
- [x] Document all functions
- [x] Check that the package builds with `devtools::check()`
- [x] Update `.travis.yml` to install Biopython (and Numpy) before running the build check
- [x] Create unit tests (using both R and Biopython to create the phylogram)
- [x] Move some of the function argument validations to a separate file for general use (e.g. validating args are not `NULL` or that they' `TRUE\FALSE` only)

### CODE REVIEW

**Comment by nsh87** [comment]
Had to rebase to enable automatic merges so the build could happen. We previously had some comments on 82dffbccfad7525ca39baa3b7a5d5ef38d4831c9. They should be addressed now.

**Comment by nsh87** [comment]
I think you need to add `@imports muscle` (and for the others in the failed build) to internal functions. Roxygen won't export to NAMESPACE with internal functions.

**Comment by nsh87** [comment]
@catterbu I think this is pretty much ready to merge into dev. If you want me wait for any reason let me know.

**Comment by catterbu** [comment]
go for it! merge away! should I worry about rebasing onto the new **dev** once you do?

**Comment by nsh87** [comment]
Awesome! Ya, you'll have to rebase. It should be pretty seamless since we mostly touch different files. You'll be able to use some of the arg validation functions I put in `R/arg_validation` afterward. They're documented, so just do `?validate_true_false` and `?validate_not_null`.

**Pull request merged**
