### PR TITLE
Add PCA legend

### PR DESCRIPTION
**Pull request by nsh87**
This is a rebase based on PR #58.

### CODE REVIEW

**Comment by catterbu** [comment]
@nsh87 looks like the one commit in this PR is the only one that is needed. As I recall, when i tried it, the colors did not always match up as desired in the legend. I may have been incorrect in this observation,  but you may check it on your local before merging it into _dev_.

**Comment by nsh87** [comment]
@catterbu: going to merge everything to dev and check it out on dev and local before pushing to production. had a bit of a hiccup today and accidentally put dev on production for a bit and there were definitely issues cluster, just a heads up. it might be worth it for you to get the site running on your local so you can test things out with the GUI. potentially much faster. a bit of a complicated set up a the moment, though.

**Comment by catterbu** [comment]
@nsh87 Are the directions for getting the site running locally on the **ReceptorMarkerFrontEnd** readme? Any idea what the particular issues are right now?

**Comment by nsh87** [comment]
@catterbu: ya they are, but i made a bunch of crazy changes recently and there are some manual migrations that must be done to take your existing installation and upgrade it to current. the alternative is for _ReceptorMarkerFrontend_ and _ReceptorMarkerBacken_ repos to just delete what you have, clone the current masters and start things up from there. That should work, but haven't tried it yet.

**Comment by catterbu** [comment]
@nsh87 okay. I have not tried running it before on Linux anyway. If you are able to tell me about any of the errors, I can start exploring them.

**Comment by nsh87** [comment]
@catterbu: I just sent you a G Drive folder with a couple files. I'd run `multi_clustering()` on the first two files after removing the unneeded columns. The second file is boolean. Then try to generate all the plots with them. The site uses `krange=2:15`, so use that, too. If there aren't any errors it should be all fine. Then try the file in the **test** folder, too and see what happens. I have a bunch of files on my local that I've played around with over the past few months. I'll get some more over to you tomorrow.

**Comment by nsh87** [comment]
@catterbu: I started some instructions to get Vagrant and VirtualBox working on Ubuntu here: https://github.com/nsh87/mimic-iii-vm/tree/dev. I need to test them on an actual Ubuntu machine, so might as well extract the relevant portion from the code block in the _Requirements_ section there.

**Pull request merged**
